id: 7e7881d6b192482ead9352a5cd58038f
initial_creation_type: TMX
origin_type: translation
source_metadata:
  id: ''
  title: Toh_134-The_Absorption_That_Encapsulates_All_Merit-v2
  language: en
  author: ''
  volume: {}
